name: Pipeline CI/CD

on:
  workflow_dispatch:
  push:
    branches: [main]

env:
  AZURE_CONTAINER_REGISTRY: fcguserapi
  CONTAINER_APP_NAME: fcg-user-api
  RESOURCE_GROUP: fcgUserApi

jobs:
  test:
    name: Running Tests
    runs-on: ubuntu-latest
    steps:
    
      - name: Download source
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Dependency Restore
        run: dotnet restore

      - name: Build with dotnet
        run: dotnet build --configuration Release --no-restore

      - name: Domain Tests
        run: dotnet test ./FCG.User.Tests.Domain/FCG.User.Tests.Domain.csproj --configuration Release --no-build --verbosity normal

      - name: Infra Tests
        run: dotnet test ./FCG.User.Tests.Infra/FCG.User.Tests.Infra.csproj --configuration Release --no-build --verbosity normal

  
  build-and-deploy:
    name: Deploy to Production
    needs: test
    if: success()
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Build
        run: dotnet build --configuration Release

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io
          username: ${{ secrets.FCGUSERAPI_REGISTRY_USERNAME }}
          password: ${{ secrets.FCGUSERAPI_REGISTRY_PASSWORD }}

      - name: Build and push container image to ACR
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_APP_NAME }}:${{ github.sha }}
          file: FCG.API/Dockerfile

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v1
        with:
          imageToDeploy: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_APP_NAME }}:${{ github.sha }}
          resourceGroup: ${{ env.RESOURCE_GROUP }}
          containerAppName: ${{ env.CONTAINER_APP_NAME }}
